### ISSUE TITLE
Incomplete Contribution Guideline

### ISSUE THREAD

**Issue by TjandraD** [sykrabadi/batamlawancorona_api#5]
In CONTRIBUTING.md, there is a section called Contribution Guideline. Which explains how to fork and run the project on a local computer. But, there are no guides on how to submit a PR whenever someone would like to contribute to this project. Maybe we could add another section or add extra steps below that part?

**Comment by sykrabadi** [comment]
Hello, I just checked your PR recently, and by far what you've written is enough for this issue. Once again, thank you very much for making this contribution guideline clearer
